language: php
php:
- 7.2
- 7.3
- 7.4
- 8.0
env:
- dependencies=lowest
- dependencies=highest
services:
- docker
before_script:
- if [ -n "$GIT_HUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GIT_HUB_TOKEN";
  fi;
- composer install
- if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable
  -n; fi;
script:
- make test
deploy:
  provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    php: '7.2'
    condition: "$dependencies = highest"
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: RPQ0ho/h3kQYdzO8C7BmcblLXu2DTVUyRBaTPRmsoL44I5e3tF1m40JuahN1ndNcMTDt84SwnyBQYJV6VCbCnCjGjjMH3ibTvqmzhzI9u/etPXUvQ7R4h5tXQ6+E0/h5RCT2WdzsByuN4Vksfa6SP4p+o6LqDJWfJxojtHw02yA=
